export default {
  FETCH_HEROS_LIST: 'FETCH_HEROS_LIST',
  FETCH_HEROS_LIST_SUCCESS: 'FETCH_HEROS_LIST_SUCCESS',
  FETCH_HEROS_SEARCH_LIST: 'FETCH_HEROS_SEARCH_LIST',
  FETCH_HEROS_SEARCH_LIST_SUCCESS: 'FETCH_HEROS_SEARCH_LIST_SUCCESS',
  FETCH_HEROS_LIST_ERROR: 'FETCH_HEROS_LIST_ERROR',
}
